# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d67d48ea4e4a7fd0789ba8b53b7c744c771e58564f09701ea67f2a2422f27eda30121a78079fda1557781060eb61629a66c45a6c31b8213bfff96555f991ea8

test:
  secret_key_base: 6c8aaccd9d098ad0c0d4f93c54d10957f24fd863a530526bc98cefe48fef9fb4de5ba0aeb69208f2aa73b2b79018d3375ca48a2d47db82bf84a3e6a28b8ecac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
